version: '{{cookiecutter.compose_version}}'
{% set nginxc    = (not cookiecutter.nginx_in_dev) and '#' or '' %}
{% set nginxnc   = (cookiecutter.nginx_in_dev) and '#' or '' %}
{% set nginxsslc = (not cookiecutter.ssl_in_dev) and '#' or '' %}
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    environment: &{{cookiecutter.app_type}}_env
       DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE:-{{cookiecutter.django_settings}}.dev}"
       NO_MIGRATE: "${NO_MIGRATE-1}"
       NO_COLLECT_STATIC: "${NO_COLLECT_STATIC-1}"
       NO_STATICS: "${NO_STATICS-1}"
    volumes: &{{cookiecutter.app_type}}_volumes
    - ./local/localdir:/local
    - ./sys:/code/sys
{%- if cookiecutter.no_local_volumes %}
{%- endif%}
{%-  if cookiecutter.use_submodule_for_deploy_code %}
    - ./{{cookiecutter.deploy_project_dir}}/sys/sudoer:/etc/sudoers.d/${APP_TYPE:-{{cookiecutter.app_type}}}
    - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/init/init.sh
    - ./{{cookiecutter.deploy_project_dir}}:/code/{{cookiecutter.deploy_project_dir}}
{%- else %}
    - ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
    - ./sys/init.sh:/code/init/init.sh
{%- endif%}
{%- if not cookiecutter.no_lib %}
    - ./lib:/code/lib
{%- endif%}
    - ./local:/code/local
{%- if cookiecutter.with_bundled_front %}
    - ./frontend:/code/frontend
{%- endif %}
    - ./src:/code/src
{%- macro django_assets() %}
    - ./docs:/code/docs
{%- if not cookiecutter.no_private %}
    - ./local/private:/code/private
{%- endif%}
    - ./local/public:/code/public
    - ./local/media:/code/public/media
    - ./local/static:/code/public/static
{%- endmacro %}
{{- django_assets() }}
    - ./tox.ini:/code/tox.ini
    - ./.tox:/code/.tox
    - ./requirements:/code/requirements
services:
  # uncomment to activate in dev
  nginx:
    {{nginxnc}}<<: [ *bypass ]
    ports:
    - "${DJANGO__HTTP_PORT:-80}:80"
    {{nginxsslc}}- "${DJANGO__HTTPS_PORT:-443}:443"
    environment: {NO_SSL: "0"}
    volumes:
    {{django_assets().strip().replace('\n', '\n{0}'.format(nginxc and nginxc or ''))}}
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: fg
    ports:
    - "${DJANGO__API_LISTEN:-0.0.0.0}:${DJANGO__API_PORT:-8000}:8000"
    - "${DJANGO__VSCODE_LISTEN:-0.0.0.0}:${DJANGO__VSCODE_PORT:-5678}:5678"
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
  db:
    ports:
    - "${DJANGO__DB_OUT_LISTEN:-0.0.0.0}:${DJANGO__DB_OUT_PORT:-{{cookiecutter.db_out_port}}}:5432"
{% if cookiecutter.with_celery %}
  celery-beat: &celery
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: celery_beat
  celery-worker:
    <<: [ *celery ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: celery_worker
{%- endif %}
  mailcatcher:
    ports:
    - "${DJANGO__MAILCATCHER_LISTEN:-0.0.0.0}:${DJANGO__MAILCATCHER_PORT:-8025}:8025"
  backup: { <<: [ *bypass ] }
  log: { <<: [ *bypass ] }
