version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    tty: true
    # latest image is only used in prod (without dev & test tools)
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-dev"
    environment:
    - DJANGO_WSGI=${DJANGO_WSGI:-{{cookiecutter.django_project_name}}.wsgi}
    depends_on:
    - db
    - redis
    working_dir: /code/src
    command: /bin/bash /code/init/init.sh
    volumes:
      {%- if not cookiecutter.remove_cron %}
      - ./crontab:/etc/cron.d/{{cookiecutter.app_type}}
      {%- endif %}
      - ./src/{{cookiecutter.django_settings.replace('.', '/')}}/instances:/code/src/{{cookiecutter.django_settings.replace('.', '/')}}/instances
      - mediafiles:/code/public/media
      - statics:/code/public/static
      - logs:/logs/
services:
  mailcatcher:
    image: corpusops/mailhog
    volumes: ["mails:/mails"]
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /mails
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_UI_WEB_PATH: /mailcatcher
      MH_AUTH_FILE: /home/mailhog/pw
    user: root
    entrypoint:
      - sh
      - -c
      - >
        chown mailhog /mails
        && pw=$$(MH_AUTH_FILE="" MailHog bcrypt "$${MAILCATCHER_PASSWORD:-mailcatcher}")
        && echo "$${MAILCATCHER_USER:-mailcatcher}:$$pw" > $$MH_AUTH_FILE
        && su mailhog -p -c MailHog
    <<: [ *env ]
  redis:
    <<: [ *env ]
    image: "{{cookiecutter.redis_image}}"
    hostname: redis
    volumes:
      - 'redis:/data'
  db:
    <<: [ *env ]
    image: "{{cookiecutter["{0}_image".format(cookiecutter.db_mode)]}}"
    volumes:
      - postgresql:/var/lib/postgresql/data
  nginx:
    <<: [ *env ]
    restart: always
    image: "{{cookiecutter.nginx_image}}"
    depends_on:
      - {{cookiecutter.app_type}}
    volumes:
      - ./prod/etc/nginx/vhost.conf.template:/etc/nginx/conf.d/default.conf.template
      - mediafiles:/public/media/:ro
      - statics:/public/static/
      - logs:/logs/
    command: >
      /bin/sh -c "
      CONF_PREFIX=DJANGO__ confenvsubst.sh /etc/nginx/conf.d/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && exec /bin/supervisord.sh"
    environment:
    - SUPERVISORD_CONFIGS=/etc/supervisor.d/cron /etc/supervisor.d/nginx
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
  {%- if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on:
      - {{cookiecutter.app_type}}
    command: /bin/sh /code/init/cron.sh
  {%-endif%}
  backup:
    <<: [ *env ]
    image: "corpusops/dbsmartbackup:pg10"
    restart: always
    volumes:
      - backupdb-dumps:/srv/backups/
      - backupdb-logs:/srv/backups/logs/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./local/backup/setup/reconfigure.yml:/setup/reconfigure.yml:ro
volumes:
  backupdb-logs:
  backupdb-dumps:
  postgresql:
  redis:
  mediafiles:
  statics:
    name: "${{'{'}}{{cookiecutter.app_type.upper()}}_NAME}-statics-${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    external: false
  logs:
  mails:
