version: '{{cookiecutter.compose_version}}'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args: &args
        BUILDKIT_INLINE_CACHE: "1"
        BASE: "${DJANGO_BASE_IMAGE:-{{cookiecutter.base_image}}}"
        HELPERS: "${HELPERS_IMAGE:-{{cookiecutter.helpers_image}}}"
        # BASE: "${{'{'}}{{cookiecutter.app_type.upper()}}}}_BASE_IMAGE:-{{cookiecutter.debian_image}}}"
        PY_VER: "${DJANGO_PY_VER:-{{cookiecutter.py_ver}}}"
        WITH_VSCODE: "${WITH_VSCODE:-0}"
        VSCODE_VERSION: "${VSCODE_VERSION-}"
services:
{%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
