version: '3.7'
{% set nginxc    = (not cookiecutter.nginx_in_dev) and '#' or '' %}
{% set nginxsslc = (not cookiecutter.ssl_in_dev) and '#' or '' %}
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  django: &django
    environment: &django_env
       DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE:-{{cookiecutter.django_settings}}.dev}"
       NO_MIGRATE: "1"
       NO_COLLECT_STATIC: "1"
       NO_STATICS: "1"
    volumes: &django_volumes
      {%-if cookiecutter.use_submodule_for_deploy_code %}
      - ./{{cookiecutter.deploy_project_dir}}/sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/sys/init.sh
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/init/init.sh
      - ./{{cookiecutter.deploy_project_dir}}/sys/etc/supervisor.d:/code/sys/etc/supervisor.d
      - ./{{cookiecutter.deploy_project_dir}}:/code/{{cookiecutter.deploy_project_dir}}
      {%-else %}
      - ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./sys/init.sh:/code/init/init.sh
      # retrocompat
      - ./sys/init.sh:/code/sys/init.sh
      - ./sys/etc/supervisor.d:/code/etc/supervisor.d
      {%- endif%}
      - ./sys/etc/cron.d:/code/sys/etc/cron.d/
{%- if not cookiecutter.no_lib %}
      - ./lib:/code/lib
{%- endif%}
      - ./local:/code/local
      - ./src:/code/src
{%- if not cookiecutter.no_private %}
      - ./private:/code/private
{%- endif%}
      - ./tox.ini:/code/tox.ini
      - ./.tox:/code/.tox
      - ./requirements.txt:/code/requirements.txt
      - ./requirements-dev.txt:/code/requirements-dev.txt
services:
  {{nginxc}}nginx:
{% if nginxc -%}
    <<: [ *bypass ]
    # uncomment to activate in dev
{%-endif%}
  {{nginxc}}  ports:
  {{nginxc}}  - "${DJANGO__HTTP_PORT:-80}:80"
  {{nginxc}}  {% if not nginxc%}{{nginxsslc}}{%endif %}- "${DJANGO__HTTPS_PORT:443}:443"
  {{nginxc}}  environment: {NO_SSL: "0"}
  {{cookiecutter.app_type}}:
    <<: [ *django ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: fg
    ports:
    - "${DJANGO__API_LISTEN:-0.0.0.0}:${DJANGO__API_PORT:-8000}:8000"
    - "${DJANGO__VSCODE_LISTEN:-0.0.0.0}:${DJANGO__VSCODE_PORT:-5678}:5678"
  db:
    ports:
    - "${DJANGO__DB_OUT_LISTEN:-0.0.0.0}:${DJANGO__DB_OUT_PORT:-{{cookiecutter.db_out_port}}}:{{cookiecutter.db_out_port}}"
{% if cookiecutter.with_celery %}
  celery-beat: &celery
    <<: [ *django ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: celery_beat
  celery-worker:
    <<: [ *celery ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: celery_worker
{% endif -%}
