version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PY_VER: "${DJANGO_PY_VER:-{{cookiecutter.py_ver}}}"
        WITH_VSCODE: "${WITH_VSCODE:-0}"
        VSCODE_VERSION: "${VSCODE_VERSION-}"
        WITH_PYCHARM: "${WITH_PYCHARM:-0}"
        PYCHARM_VERSION: "${PYCHARM_VERSION-}"
        BASE: "${DJANGO_BASE_IMAGE:-{{cookiecutter.base_image}}}"
services:
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
