---
{{cookiecutter.app_type}}_servers: {{cookiecutter.lname}}_servers
cops_{{cookiecutter.app_type}}_name: "{{cookiecutter.lname}}"
cops_django_project_module_name: "{{cookiecutter.django_project_name}}"
cops_{{cookiecutter.app_type}}_tld_domain: "{{cookiecutter.tld_domain}}"
cops_{{cookiecutter.app_type}}_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_{{cookiecutter.app_type}}_docker_image: "{{cookiecutter.docker_image}}"
cops_{{cookiecutter.app_type}}_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_{{cookiecutter.app_type}}_docker_tag: "{{'{{'}}cops_{{cookiecutter.app_type}}_gitref.replace('master', 'latest')}}"
cops_django_gunicorn_class: "{{cookiecutter.gunicorn_class}}"
{% if 'post' in cookiecutter.db_mode -%}
cops_{{cookiecutter.app_type}}_postgres_startup_timeout: 45s
{%- endif %}
{% if cookiecutter.with_celery -%}
cops_{{cookiecutter.app_type}}_rabbitmq_user: rabbit
cops_{{cookiecutter.app_type}}_rabbitmq_password: rabbitpw
{%- endif%}
cops_{{cookiecutter.app_type}}_docker_env_extra: |-
  # db
  {% if cookiecutter.with_celery -%}
  {% if cookiecutter.celery_broker == 'rabbitmq' %}RABBITMQ_DEFAULT_USER={{'{{'}}cops_{{cookiecutter.app_type}}_rabbitmq_user}}
  RABBITMQ_DEFAULT_PASS={{'{{'}}cops_{{cookiecutter.app_type}}_rabbitmq_password}}{% endif %}
  {%- endif %}
  {% if 'post' in cookiecutter.db_mode %}POSTGRES_STARTUP_TIMEOUT={{'{{'}}cops_{{cookiecutter.app_type}}_postgres_startup_timeout}}{% endif %}
cops_django_restarted_services: "{{"{{"}}cops_django_restarted_services_default{% if cookiecutter.cache_system %}.replace(
    'redis', '{{cookiecutter.cache_system}}'){%endif
    %}.replace(' django', ' django{% 
    if cookiecutter.with_celery%} celery-broker celery-beat celery-worker{%endif
    %}{% if 'post' in cookiecutter.db_mode%} setup-postgres{%endif%}')}}"
cops_django_http_protect_user: "root"
cops_django_http_protect_password: "rootroot"
{% set jscomment = (not cookiecutter.with_bundled_front) and '#  ' or '' %}
{{jscomment}}# cops_django_code_sync_theme_contents: "{{'{{'}}cops_django_code_sync_theme_contents_front}}"
{{jscomment}}cops_django_code_sync_theme_contents: "{{'{{'}}cops_django_code_sync_theme_contents_webpack}}"
